export const SEARCH_CHANNEL = "SEARCH_CHANNEL";
export const SEARCH_CHANNEL_FAIL = "SEARCH_CHANNEL_FAIL";
export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";
export const SEARCH_USER_FOLLOWERS = "SEARCH_USER_FOLLOWERS";
export const SEARCH_USER_FOLLOWERS_FAIL = "SEARCH_USER_FOLLOWERS_FAIL";
